### ISSUE TITLE
Possible error in the implementation of objective_function

### ISSUE THREAD

**Issue by manonthegithub** [automl/nas_benchmarks#13]
I suspect that in this line you should have `budget` and not the constant 100 in the divisor:
https://github.com/automl/nas_benchmarks/blob/50ac6126b54159a6f592a30f777f4ffa1286f0f8/tabular_benchmarks/fcnet_benchmark.py#L54
and here:
https://github.com/automl/nas_benchmarks/blob/50ac6126b54159a6f592a30f777f4ffa1286f0f8/tabular_benchmarks/fcnet_benchmark.py#L76
and here:
https://github.com/automl/nas_benchmarks/blob/50ac6126b54159a6f592a30f777f4ffa1286f0f8/tabular_benchmarks/fcnet_benchmark.py#L96

**Comment by manonthegithub** [comment]
Now I think, I am probably wrong. You have 100 because you have pretrained models for 100 epochs?

**Comment by aaronkl** [comment]
yes that's correct probably one should make that more clear
