### ISSUE TITLE
Handling of objective function evaluation in Regularized Evolution script

### ISSUE THREAD

**Issue by Neeratyoy** [automl/nas_benchmarks#16]
Hi,

This is wrt fcnet_tabular_benchmarks.

The Regularized Evolution script evaluates accuracy by subtracting the `objective_function()` evaluation from 1.

However, for certain benchmarks the MSE returned is greater than 1, which can make the accuracy negative. Is [this](https://github.com/automl/nas_benchmarks/blob/master/experiment_scripts/run_regularized_evolution.py#L74) evaluation correct?
Accuracies are computed [here](https://github.com/automl/nas_benchmarks/blob/master/experiment_scripts/run_regularized_evolution.py#L125) and [here](https://github.com/automl/nas_benchmarks/blob/master/experiment_scripts/run_regularized_evolution.py#L147).

One way to verify this may be so:
> b = FCNetSliceLocalizationBenchmark(data_dir)
> cs = b.get_configuration_space()
>
> for i in range(1000):
> &nbsp;&nbsp;&nbsp;&nbsp; config = cs.sample_configuration()
> &nbsp;&nbsp;&nbsp;&nbsp; value, _ = b.objective_function(config)
> &nbsp;&nbsp;&nbsp;&nbsp; if value > 1:
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; print(config)
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; break
> for i in range(6):
> &nbsp;&nbsp;&nbsp; value, _ = b.objective_function(config)
> &nbsp;&nbsp;&nbsp; print(1 - value)

**Comment by aaronkl** [comment]
Good catch. It should be probably just -y instead of 1-y since RE is maximizing, even better would be to change it completely such that it minimizes the objective function. However, I don't think that changes anything on the results. Could you send a PR to fix that?
